### ISSUE TITLE
pycrypto doesn't compile on windows

### ISSUE THREAD

**Issue by codytodonnell** [mozilla/mozilla-django-oidc#156]
Despite attempting several different installation methods, I always receive the following error:

```
c:\users\codonnell\appdata\local\programs\python\python36-32\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\codonnell\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\CODONN~1\\AppData\\Local\\Temp\\pip-build-vmywdjq0\\pycrypto\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\CODONN~1\AppData\Local\Temp\pip-h376pd9t-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\CODONN~1\AppData\Local\Temp\pip-build-vmywdjq0\pycrypto\ 
```

I have installed Visual Studio Community 2017 and Visual C++ 2015 Build Tools.

I tried installing the package with wheel (found [here](https://pypi.python.org/pypi/mozilla-django-oidc)) but got the same error. Also tried installing with the .tar.gz file on that page but again got the same error.

Any clue what could be causing this issue? Are there alternative ways to install the library?

I'm on Windows 10, using pip 9.0.1 and python 3.6.

**Comment by willkg** [comment]
Is that the only output you get from trying to install mozilla-django-oidc?

If so, I'm guessing it's dying on installing pycrypto which is a dependency of python-jose which mozilla-django-oidc uses.

I don't compile Python libraries on Windows, so I'm just guessing, but after doing a Google search, seems like this might be helpful:

https://stackoverflow.com/questions/11405549/how-do-i-install-pycrypto-on-windows

If it's not, I'd suggest checking out the pycrypto docs and issue tracker and whatever they have for support and see if you can find answers there.

Hope that helps!

**Comment by codytodonnell** [comment]
Yes this lead to a solution!

I installed one of the pycrypto binaries from the link in the SO answer:

`easy_install http://www.voidspace.org.uk/python/pycrypto-2.6.1/pycrypto-2.6.1.win-amd64-py3.4.exe`

And after that I was able to successfully install mozilla-django-oidc using pip.

Thanks!

**Comment by codytodonnell** [comment]
Hate to do this but I spoke too soon...

After installing pycrypto through easy_install I was able to install mozilla-django-oidc using pip without any errors, but the pycrypto library still seems like it wasn't installed correctly.

Upon hitting the authorize endpoint, my app is redirected to the callback URL, at which point I receive the following error:

`ImportError: DLL load failed: The specified module could not be found.`

Full output:

`Internal Server Error: /oidc/callback/
Traceback (most recent call last):
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mozilla_django_oidc\views.py", line 75, in get
    self.user = auth.authenticate(**kwargs)
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\contrib\auth\__init__.py", line 68, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\contrib\auth\__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\contrib\auth\__init__.py", line 23, in load_backend
    return import_string(path)()
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\utils\module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mozilla_django_oidc\auth.py", line 12, in <module>
    from jose import jws
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jose\jws.py", line 8, in <module>
    from jose import jwk
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\jose\jwk.py", line 13, in <module>
    from Crypto.PublicKey import RSA
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pycrypto-2.6-py3.6-win32.egg\Crypto\PublicKey\RSA.py", line 78, in <module>
    from Crypto import Random
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pycrypto-2.6-py3.6-win32.egg\Crypto\Random\__init__.py", line 28, in <module>
    from Crypto.Random import OSRNG
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pycrypto-2.6-py3.6-win32.egg\Crypto\Random\OSRNG\__init__.py", line 34, in <module>
    from Crypto.Random.OSRNG.nt import new
  File "C:\Users\CODONNELL\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pycrypto-2.6-py3.6-win32.egg\Crypto\Random\OSRNG\nt.py", line 28, in <module>
    from . import winrandom
ImportError: DLL load failed: The specified module could not be found.
[26/Jun/2017 16:48:48] "GET /oidc/callback/?code=Sqa7fc&state=ZG60Oacaa9GiVrMeYRZUQGkBe2AGSHbM HTTP/1.1" 500 194151`

From searching around, it sounds like the problem is that there is not a straightforward C compiler for python 3.6 on Windows. This article steps through a very convoluted solution but this is less than ideal.

It also sounds like pycrypto is no longer maintained. If this is a frequent issue for Windows/python3 users (which I'm curious if it is), perhaps future releases of mozilla-django-oidc could look into using a different cryptographic library.

**Comment by willkg** [comment]
I don't think any Mozilla sites are using Windows, so I'm not going to work on fixing this. It sounds like it's a problem with pycrypto not building on Windows. mozilla-django-oidc doesn't use pycrypto directly, but uses python-jose which uses pycrypto.

I'm going to fix the summary of this to make it clearer.

**Comment by willkg** [comment]
We (maintainers) had a talk and none of us use Windows and we don't see how we can support Windows effectively.

Given that, I'm going to close this out and add a note that we don't support Windows.
