### ISSUE TITLE
TypeError on sending payload to josepy (py 3.6)

### ISSUE THREAD

**Issue by peterbe** [mozilla/mozilla-django-oidc#189]
I just tried to upgrade to mozilla-django-oidc 0.4.0 and it meant I had to add `josepy==1.0.0` and `pyOpenSSL==17.3.0`.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 137, in run
 self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
 response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in get_response
 response = self._middleware_chain(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
 response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
 response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
 response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
 response = self._get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
 response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
 response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
 return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
 return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mozilla_django_oidc/views.py", line 75, in get
 self.user = auth.authenticate(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
 user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 115, in _authenticate_with_backend
 return backend.authenticate(*args, **credentials)
  File "/usr/local/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 165, in authenticate
 if self.verify_token(id_token, nonce=nonce):
  File "/usr/local/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 114, in verify_token
 key,
  File "/usr/local/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 85, in _verify_jws
 jws = JWS.from_compact(payload)
  File "/usr/local/lib/python3.6/site-packages/josepy/jws.py", line 305, in from_compact
 protected, payload, signature = compact.split(b'.')
TypeError: must be str or None, not bytes
```

**Comment by peterbe** [comment]
@willkg @akatsoulas @johngian Seen this already?
I'm a bit surprised our tests didn't catch this. Perhaps there was a rush to switch to josepy. 
I can attempt a patch to this today.

**Comment by peterbe** [comment]
`jws.Header.from_compact` [expects a byte string](https://github.com/jezdez/josepy/blob/f8b3c058fa1ba91b19f828c9c32cb0ef752ca4cf/src/josepy/jws.py#L301) but in `auth.py` we're sending it a unicode string.

**Comment by peterbe** [comment]
Just making it a byte string wasn't hard but now I run into this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mozilla_django_oidc/views.py", line 75, in get
    self.user = auth.authenticate(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 115, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/usr/local/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 167, in authenticate
    if self.verify_token(id_token, nonce=nonce):
  File "/usr/local/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 116, in verify_token
    key,
  File "/usr/local/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 87, in _verify_jws
    jwk = JWK.load(key)
  File "/usr/local/lib/python3.6/site-packages/josepy/jwk.py", line 109, in load
    key = cls._load_cryptography_key(data, password, backend)
  File "/usr/local/lib/python3.6/site-packages/josepy/jwk.py", line 83, in _load_cryptography_key
    return loader(data, backend)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization.py", line 24, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1019, in load_pem_public_key
    mem_bio = self._bytes_to_bio(data)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 437, in _bytes_to_bio
    data_char_p = self._ffi.new("char[]", data)
TypeError: initializer for ctype 'char[]' must be a bytes or list or tuple, not str
```

Perhaps @jezdez should have a look at this issue.

**Comment by johngian** [comment]
Yeah i am surprised this went through the tests. I've only tested with a python 2.7 project and everything went smoothly. In the future, we should test with a python 3 env as well.

**Comment by peterbe** [comment]
If I apply this diff,
```diff
113,114c113,114
<             smart_bytes(token),
<             smart_bytes(key),
---
>             token,
>             key,
```
to `mozilla_django_oidc/auth.py` I can log in again using 0.4.0.
