### ISSUE TITLE
Unable to generate docs locally

### ISSUE THREAD

**Issue by peterbe** [mozilla/mozilla-django-oidc#210]
I created a new vitualenv (based on 3.6) and pip installed `Sphinx`. Then tried to run `make docs`:

```
(mozilla-django-oidc)
dev/DJANGO/mozilla-django-oidc  master ✗                                                                                                                                                                   22d ⚑ ◒
▶ make docs
rm -f docs/mozilla-django-oidc.rst
rm -f docs/modules.rst
sphinx-apidoc -o docs/ mozilla_django_oidc
File docs/mozilla_django_oidc.rst already exists, skipping.
Creating file docs/modules.rst.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C docs clean
rm -rf _build/*
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C docs html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 9 source files that are out of date
updating environment: 9 added, 0 changed, 0 removed
../CONTRIBUTING.rst:106: WARNING: Unexpected indentation.
../CONTRIBUTING.rst:108: WARNING: Block quote ends without a blank line; unexpected unindent.
WARNING: autodoc: failed to import module 'mozilla_django_oidc.auth'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 140, in import_module
    __import__(modname)
  File "/Users/peterbe/dev/DJANGO/mozilla-django-oidc/mozilla_django_oidc/auth.py", line 8, in <module>
    from django.contrib.auth.backends import ModelBackend
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/django/contrib/auth/backends.py", line 2, in <module>
    from django.contrib.auth.models import Permission
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/django/db/models/base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/django/apps/registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

WARNING: autodoc: failed to import module 'mozilla_django_oidc.urls'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 140, in import_module
    __import__(modname)
  File "/Users/peterbe/dev/DJANGO/mozilla-django-oidc/mozilla_django_oidc/urls.py", line 8, in <module>
    CALLBACK_CLASS_PATH = import_from_settings('OIDC_CALLBACK_CLASS', DEFAULT_CALLBACK_CLASS)
  File "/Users/peterbe/dev/DJANGO/mozilla-django-oidc/mozilla_django_oidc/utils.py", line 15, in import_from_settings
    return getattr(settings, attr, args[0])
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting OIDC_CALLBACK_CLASS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.


Exception occurred:
  File "/Users/peterbe/virtualenvs/mozilla-django-oidc/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested settings, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
The full traceback has been saved in /var/folders/1x/2hf5hbs902q54g3bgby5bzt40000gn/T/sphinx-err-55nrlbec.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[1]: *** [html] Error 2
make: *** [docs] Error 2
```

What should I set the `DJANGO_SETTINGS_MODULE` to and how do you build the docs locally?

**Comment by akatsoulas** [comment]
I am getting a few warnings but the build runs successfully. I tried this in a clean virtualenv with python3.6 and only sphinx installed via pip. The only way that I managed to get an error for the `DJANGO_SETTINGS_MODULE` is when I deactivated the venv. Is there any possibility to be the same case here?

**Comment by peterbe** [comment]
What did you set `DJANGO_SETTINGS_MODULE` to before you ran `sphinx`?

**Comment by akatsoulas** [comment]
I managed to reproduce this after recreating the venv. I opened #214 which add the tests settings in the Sphinx conf.
