### ISSUE TITLE
Could not find a suitable TLS CA certificate bundle, invalid path: false

### ISSUE THREAD

**Issue by strus38** [mozilla/mozilla-django-oidc#382]
Hi

I am deploying Netbox on K8S and I am trying to add OIDC with keycloak to allow SSO on Netbox.
So I have done the necessary changes - I guess - but failing on SSL certificates with the following error:
```
Environment:


Request Method: GET
Request URL: http://netbox.home.lab/oidc/callback/?state=JQLaEaBtEhYLidXMYrFFLffNFh1jth9Q&session_state=bc53beb4-9cb2-4bcb-9938-fc0a30a66d05&code=2b53a3e7-a893-4940-80b5-b430f05da90f.bc53beb4-9cb2-4bcb-9938-fc0a30a66d05.0484b399-6e9d-48a0-8e5c-d305ea20485a

Django Version: 3.1
Python Version: 3.7.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'mozilla_django_oidc',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'cacheops',
 'corsheaders',
 'debug_toolbar',
 'django_filters',
 'django_tables2',
 'django_prometheus',
 'mptt',
 'rest_framework',
 'taggit',
 'timezone_field',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'secrets',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'django_rq',
 'drf_yasg']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'utilities.middleware.ExceptionHandlingMiddleware',
 'utilities.middleware.RemoteUserMiddleware',
 'utilities.middleware.LoginRequiredMiddleware',
 'utilities.middleware.APIVersionMiddleware',
 'extras.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mozilla_django_oidc/views.py", line 99, in get
    self.user = auth.authenticate(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.7/site-packages/mozilla_django_oidc/auth.py", line 276, in authenticate
    token_info = self.get_token(token_payload)
  File "/usr/local/lib/python3.7/site-packages/mozilla_django_oidc/auth.py", line 228, in get_token
    proxies=self.get_settings('OIDC_PROXY', None))
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 228, in cert_verify
    "invalid path: {}".format(cert_loc))

Exception Type: OSError at /oidc/callback/
Exception Value: Could not find a suitable TLS CA certificate bundle, invalid path: false

```
I have used those params:
```
OIDC_RP_CLIENT_ID: netbox
OIDC_RP_CLIENT_SECRET: 65345fa6-e4fd-4913-a752-a274a7a87d96
OIDC_OP_AUTHORIZATION_ENDPOINT: https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/auth
OIDC_OP_TOKEN_ENDPOINT: https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/token
OIDC_OP_USER_ENDPOINT: https://keycloak.home.lab/auth/realms/master/protocol/openid-connect/userinfo
LOGIN_REDIRECT_URL: /
LOGOUT_REDIRECT_URL: /
OIDC_OP_JWKS_ENDPOINT:
OIDC_RP_SIGN_ALGO: HS256
OIDC_RP_IDP_SIGN_KEY:
OIDC_VERIFY_SSL: false
```

Weird thing is that on that netbox pod, trying to read keycloak works without certificates complaints:
```
bash-5.0# wget https://keycloak.home.lab
Connecting to keycloak.home.lab (10.0.0.10:443)
saving to 'index.html'
index.html           100% |*************************************************************************************************************************|  1087  0:00:00 ETA 
'index.html' saved
```

The *.home.lab certificate has been pushed in `/etc/ssl/certs/ca-certificates.crt`

Any hints?
Thanks!

**Comment by strus38** [comment]
well ... some progress since the False was badly set... now 'bytes' object has no attribute 'verifier'

**Comment by strus38** [comment]
I also tries with RS256 algorithm, it is failing with: `'bytes' object has no attribute 'verifier'`
However all seem correct:
In ` payload_data = self.get_payload_data(token, key) `
```
key | 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkMajTF5JfM7+Bq3vuxo0b1uScGV2yuhcALhYng16GvkBpMi0HbiHbKlU6RVSLIDkJrSRg1zBhwkticiETKaxyRjhzyidumrhbHbKe6J//jlgD6W6x8GIeOOVclb1ioSPrcY/HF//6zq6V1hvL+MlSXS5FXau3ss2Pnh3QvOghwnYZsG7xGu9ZnfEoTuZMAbLMzsR7lnU4ZF74WxC9T9b5+gID5TddKY94j+lXpDEaUE3/jAy+cb1w0hfsYVXknxo/GCDcB2PmBkJbs9c7FiY2WbTL5Cgu5Deag9v6IJ1Yj5Nz6apv1+bGOqqTOnhGi62DcebKSUNTUCt8K+U5yYBaQIDAQAB\n'
-- | --
kwargs | {'nonce': 'TXYU8AXzWCKzAD2UHPpVxAfSIpNtdATW'}
nonce | 'TXYU8AXzWCKzAD2UHPpVxAfSIpNtdATW'
self | <mozilla_django_oidc.auth.OIDCAuthenticationBackend object at 0x7f96fc56e2d0>
token | (b'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJUb29seUZtX2dkaG15XzRaSzRF'  b'MGQ5bFRaUVdmbWpnWEJSUVRqMkRuZ2RzIn0.eyJleHAiOjE2MDQxMzg5OTMsImlhdCI6MTYwNDEz'  b'ODkzMywiYXV0aF90aW1lIjoxNjA0MTM4NzQ2LCJqdGkiOiJjODg0ZmY3Mi02NzM4LTQ1NzEtOWJl'  b'MS0xMTc1NmNkYzlkMDYiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLmhvbWUubGFiL2F1dGgvcmVh'  b'bG1zL21hc3RlciIsImF1ZCI6Im5ldGJveCIsInN1YiI6IjVhNmVmNWQ3LWI2YzktNDk1Yi05NjM5'  b'LTY0NmI3NTRkNGYwMCIsInR5cCI6IklEIiwiYXpwIjoibmV0Ym94Iiwibm9uY2UiOiJUWFlVOEFY'  b'eldDS3pBRDJVSFBwVnhBZlNJcE50ZEFUVyIsInNlc3Npb25fc3RhdGUiOiI3MDg4YTUzMC0wMTIw'  b'LTQ2ZTYtODNmNy0yOTg4YzYyYWY4YjgiLCJhY3IiOiIwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNl'  b'LCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJrZXljbG9hayJ9.aFGu1rXnTzDjX6JBmXJJsrsIftzGLIk'  b'ZxwktgXHCJ8SYD3qbMC0LnpZy_mvQcyCgl0pL4f9a_OrCsUWdn9CDWYrMYwn5drGCJ565uUMJZXw'  b'SiAjCU0BXmQA7Ggtpi03iJ5XYRpAjDJDSTj3Jpb7IFDohnI4R31nxnzGOoTtr1H6CQPrOUmiExfi'  b'PW9eyaNdeNhX1iO8iVffzBFplv69dywmSubmgc-_pgrCQl5CnzI2dotlW2iKZMPtUMhUfIrBTIri'  b'T-0_oPo2OAiu1x9I-bADnCg-UllfEYkD-82j87hq3iI_Pz3yH3VsOMVjm3O93CulXgJIfWVCi_g3'  b'nZR01Sg')
```
If I take the token and the key, all seem perfect ...
![image](https://user-images.githubusercontent.com/5890515/97776632-01772180-1b6a-11eb-93e0-30a677450c88.png)

So what is happening??

**Comment by strus38** [comment]
I could move forward by replacing the token key by the JWT endpoint ... but then fails with the other defect I opened.

**Comment by pedromendes96** [comment]
@strus38  any extra information why HS256 doesn't work?

**Comment by strus38** [comment]
I think the user info is not decoded cf the code.

Le ven. 20 nov. 2020 à 16:56, Pedro Mendes <notifications@github.com> a
écrit :

**Comment by variable** [comment]
I was having the same problem with HS256, then I changed to RS256 and define the `OIDC_OP_JWKS_ENDPOINT` then it worked

```python
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_OP_JWKS_ENDPOINT = 'https://keycloak-dev/auth/realms/test/protocol/openid-connect/certs'
```

**Comment by leuat** [comment]
I'm having the same problem with HS256 (JWS token verification failed), but when changing to RS256 and define OIDC_OP_JWKS_ENDPOINT to ../certs, I get an json parser exception.. see  https://github.com/mozilla/mozilla-django-oidc/issues/421
