### ISSUE TITLE
Problems with mozilla-django-oidc callback 

### ISSUE THREAD

**Issue by leuat** [mozilla/mozilla-django-oidc#421]
Hi there! OIDC & django n00b here, so please bear with me. 

Set up mozilla-django-oidc on a https apache server with rs256 and correct  endpoints (OIDC_OP_JWKS_ENDPOINT,OIDC_RP_SIGN_ALGO,OIDC_OP_TOKEN_ENDPOINT, OIDC_OP_AUTHORIZATION_ENDPOINT) all set etc. 

I manage to log in - but afterwards, the server crashes with a json format error (basically crashing on  "self.user = auth.authenticate(**kwargs)" in the MDO views.py 

I have no idea what is going on here, and I'm unable to find any information on google about what this error could mean - any tips would be helpful!

python 3.6, django 3.2.4, mozilla-django-oidc 1.2.4

<img width="725" alt="Screenshot 2021-06-15 at 16 30 07" src="https://user-images.githubusercontent.com/5620670/122071505-10f46380-cdf7-11eb-8165-0d6fc688f167.png">

**Comment by leuat** [comment]
`Environment:


Request Method: GET
Request URL: https://www.nutil.org/oidc/callback/?state=UcE4K8MaU5FsnwgeenrAOWR72YdhQxOT&session_state=cb1ce972-0be7-4427-8bb5-78ff8449e728&code=243462ae-5bb1-4d11-9faa-fe3dc45d534d.cb1ce972-0be7-4427-8bb5-78ff8449e728.360bb004-2b5f-4d68-bcb0-c71b030be07c

Django Version: 3.2.4
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'mozilla_django_oidc']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/mozilla_django_oidc/views.py", line 99, in get
    self.user = auth.authenticate(**kwargs)
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 76, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 286, in authenticate
    return self.get_or_create_user(access_token, id_token, payload)
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 307, in get_or_create_user
    user_info = self.get_userinfo(access_token, id_token, payload)
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/mozilla_django_oidc/auth.py", line 245, in get_userinfo
    return user_response.json()
  File "/home/ubuntu/nutilweb/nutilenv/lib/python3.6/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

Exception Type: JSONDecodeError at /oidc/callback/
Exception Value: Expecting value: line 2 column 1 (char 1)
`

**Comment by variable** [comment]
Any chance you can display the json content?

**Comment by leuat** [comment]
Sorry, been away for the summer - back now, problem still persists

when printing out the corrupted json, there's actually an error message here :

AnonymousUser
None
AnonymousUser
<Response [200]>
Internal Server Error: /oidc/callback

any ideas?

**Comment by leuat** [comment]
Back from holdays, gotta look into this again. 

in auth.py "get_userinfo", user_response.json() crashes - also whenever I'm trying to print it to the log, so the format conversion fails (sys.stderr.write(user_response.json() crashes with the same message). Any ideas on how to actually view the response object?

**Comment by rhclayto** [comment]
> resolved

How did you resolve it? I'm having the same problem.

**Comment by yasirgit** [comment]
> resolved

How did you resolve this? Can I get some references? Struggling with the same issue. 
![image](https://github.com/mozilla/mozilla-django-oidc/assets/3036313/42d706df-b876-4b35-9078-c1d83a0ffc29)
