### ISSUE TITLE
401 Client Error: Unauthorized for url [mozilla-django-oidc - Keycloack]

### ISSUE THREAD

**Issue by sagarguptay2j** [mozilla/mozilla-django-oidc#483]
After i am logged in into keycloak server i am facing error in the login callback
HTTPError at /oidc/callback/
This is my settings
OIDC_RP_CLIENT_ID = "voice-dashboard"
OIDC_RP_CLIENT_SECRET = "c2gpXYAZ30JJJ1lHt06MoXLGklo3iPLE"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_OP_JWKS_ENDPOINT = "http://host.docker.internal:8080/realms/SquadStack/protocol/openid-connect/certs"
OIDC_OP_AUTHORIZATION_ENDPOINT = "http://localhost:8080/realms/SquadStack/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = "http://host.docker.internal:8080/realms/SquadStack/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = "http://host.docker.internal:8080/realms/SquadStack/protocol/openid-connect/userinfo"
LOGIN_REDIRECT_URL = "http://0.0.0.0:8001/voice/dashboard/index/"
LOGOUT_REDIRECT_URL = "http://0.0.0.0:8001/voice/dashboard/index/"

here is the django. logs:
django_web3       | [02/Jan/2023 16:03:17] "GET /oidc/authenticate/?next=/voice/dashboard/index/ HTTP/1.1" 302 0
keycloak          | 2023-01-02 10:33:18,015 WARN  [org.keycloak.events] (executor-thread-97) type=USER_INFO_REQUEST_ERROR, realmId=799595e1-4acc-4b49-b25b-a6826734d9a7, clientId=null, userId=null, ipAddress=172.18.0.1, error=invalid_token, auth_method=validate_access_token
django_web3       | django 02/Jan/2023:10:33:18,017550 +0000 [ERROR] django.request: thread=281473743839712 extra:request=<WSGIRequest:GET'/oidc/callback/?state=UqHSfoObYqzrF3Vkbu0mzn9TGg8nEN0I&session_state=7b8fa067-293b-4d03-86b2-40342269fe35&code=7a015f5c-9338-460a-83f0-5e989525145a.7b8fa067-293b-4d03-86b2-40342269fe35.dae5f6dc-c4b2-453f-ab71-3c2060d5ebc5'>&status_code=500 Internal Server Error: /oidc/callback/
django_web3       | Traceback (most recent call last):
django_web3       |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
django_web3       |     response = self.process_exception_by_middleware(e, request)
django_web3       |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
django_web3       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_web3       |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
django_web3       |     return self.dispatch(request, *args, **kwargs)
django_web3       |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
django_web3       |     return handler(request, *args, **kwargs)
django_web3       |   File "/usr/local/lib/python3.5/site-packages/mozilla_django_oidc/views.py", line 88, in get
django_web3       |     self.user = auth.authenticate(**kwargs)
django_web3       |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
django_web3       |     user = backend.authenticate(**credentials)
django_web3       |   File "/usr/local/lib/python3.5/site-packages/mozilla_django_oidc/auth.py", line 242, in authenticate
django_web3       |     return self.get_or_create_user(access_token, id_token, verified_id)
django_web3       |   File "/usr/local/lib/python3.5/site-packages/mozilla_django_oidc/auth.py", line 259, in get_or_create_user
django_web3       |     user_info = self.get_userinfo(access_token, id_token, verified_id)
django_web3       |   File "/usr/local/lib/python3.5/site-packages/mozilla_django_oidc/auth.py", line 202, in get_userinfo
django_web3       |     user_response.raise_for_status()
django_web3       |   File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 943, in raise_for_status
django_web3       |     raise HTTPError(http_error_msg, response=self)
django_web3       | requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://host.docker.internal:8080/realms/SquadStack/protocol/openid-connect/userinfo
django_web3       | django 02/Jan/2023:10:33:18,059817 +0000 [INFO] qinspect.middleware: thread=281473743839712 extra: [SQL] 0 queries (0 duplicates), 0 ms SQL time, 106 ms total request time

same issue is posted on [SO](https://stackoverflow.com/questions/74813119/401-client-error-unauthorized-for-url-mozilla-django-oidc-keycloack/74980320?noredirect=1#comment132319383_74980320)

**Comment by sagarguptay2j** [comment]
It is similar to issue #481 but the fix provided is unclear or it doesn't solved my issue can someone please check the problem here

**Comment by sagarguptay2j** [comment]
I used kubernetes.docker.internal as domain name instead of localhost and keycloak which resolves my problem My changed settings:

KEYCLOACK_BASE_URI = "http://kubernetes.docker.internal:8080"
KEYCLOACK_REALM_NAME = "SquadStack"
OIDC_AUTH_URI = KEYCLOACK_BASE_URI + "/realms/" + KEYCLOACK_REALM_NAME
OIDC_OP_JWKS_ENDPOINT = OIDC_AUTH_URI + "/protocol/openid-connect/certs"
OIDC_OP_AUTHORIZATION_ENDPOINT = OIDC_AUTH_URI + "/protocol/openid-connect/auth"
OIDC_OP_TOKEN_ENDPOINT = OIDC_AUTH_URI + "/protocol/openid-connect/token"
OIDC_OP_USER_ENDPOINT = OIDC_AUTH_URI + "/protocol/openid-connect/userinfo"
OIDC_OP_LOGOUT_ENDPOINT = OIDC_AUTH_URI + "/protocol/openid-connect/logout"
